corrections for substation diagram
powsybl/powsybl-single-line-diagram pull request #180
Opened 2020-10-20 10:11 UTC by FranckLecuyer

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2020-10-20 11:41 UTC, floriand-e2r commented
The two-winding transformer is correctly rotated in substation.svg, but alas! it's still suffering a 90° rotation in substation_no_feeder_values.svg and substation_optimized.svg

2020-10-20 12:02 UTC, floriand-e2r commented
I got it, it's because the substation graph is "damaged" when generating the SVG file. In fact this explains the issues #178 and #177 that I just created. To "correct" it, the substation graph needs to be fresh new when writing the svg in the tests...
Was this already known?

2020-10-20 13:28 UTC, FranckLecuyer commented
> I got it, it's because the substation graph is "damaged" when generating the SVG file. In fact this explains the issues #178 and #177 that I just created. To "correct" it, the substation graph needs to be fresh new when writing the svg in the tests...
> Was this already known?

I have just corrected that in this PR : Thanks for having seen that ....

2020-10-20 17:35 UTC, floriand-e2r requested changes
Could you also fill the PR description briefly?

2020-10-21 09:30 UTC, FranckLecuyer commented on single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java
> +                if (!node.isRotated() || Math.abs(node.getRotationAngle()) == 180.) {
Corrected

2020-10-21 09:31 UTC, FranckLecuyer commented on single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DefaultDiagramStyleProvider.java
> +                        if (!node.isRotated()) {
Conditions changed

2020-10-21 12:23 UTC, floriand-e2r approved these changes

2020-11-03 08:05 UTC, merged