Updating getting started of README.md
powsybl/powsybl-single-line-diagram pull request #186
Opened 2020-10-27 12:39 UTC by floriand-e2r

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?**
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Docs update

**What is the current behavior?** *(You can also link to an open issue here)*
Getting started section of README.md not working

**What is the new behavior (if this is a feature change)?**
Getting started section of README.md working

2020-10-27 13:45 UTC, floriand-e2r commented
The getting started section could be on powsybl website instead, then we'd just link the corresponding page here. Would you agree @mathbagu?

2020-11-05 08:26 UTC, geofjamg approved these changes

2020-11-12 12:47 UTC, geofjamg requested changes
On the second picture could lyou activate the height compaction?

2020-12-03 08:38 UTC, floriand-e2r commented
Do not merge before the related API guide webpage is deployed.

2021-01-04 11:56 UTC, geofjamg approved these changes

2021-01-07 14:58 UTC, merged