use ServiceLoader.load with the current classloader instead of the context classloader
powsybl/powsybl-single-line-diagram pull request #240
Opened 2021-05-11 06:35 UTC by jonenst

The context classloader can be the wrong one (and ServiceLoader.load returns an empty list)
when you are calling ServiceLoader.load in the ForkJoinPool.commonPool() (or any other thread pool)
and you have your classes in another classloader than the AppClassLoader (=system classloader).
This is the case when using a springboot fat jar, or when deploying the code in a war in an application
server, or when using mvn exec:java

Signed-off-by: Jon Harper <jon.harper87@gmail.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
https://github.com/powsybl/powsybl-core/pull/1727

2021-05-12 12:51 UTC, flo-dup approved these changes

2021-05-12 12:57 UTC, flo-dup requested changes
Don't we also need to change the `ServiceLoaderCache` used in `NetworkGraphBuilder`? Indeed, it may use the wrong context classloader (in `ServiceLoaderCache::getServices`)

2021-05-17 08:11 UTC, jonenst commented
@flo-dup  ServiceLoaderCache was modified in core https://github.com/powsybl/powsybl-core/pull/1727 so it should be fixed when we upgrade

2021-05-17 08:18 UTC, flo-dup approved these changes

2021-05-17 08:19 UTC, merged