Replace components xml file by json file (issue #238)
powsybl/powsybl-single-line-diagram pull request #276
Opened 2021-09-17 13:02 UTC by tadam50

Signed-off-by: Thomas ADAM <tadam@silicom.fr>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
'#238'

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
Using JAXB dependency

**What is the new behavior (if this is a feature change)?**
No JAXB dependency needed

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2021-09-17 14:23 UTC, flo-dup requested changes
Great, just a few minor comments

2021-09-17 14:23 UTC, flo-dup commented on single-line-diagram-core/src/test/java/com/powsybl/sld/library/ComponentsTest.java
>          Components components;
Very minor but you can merge that line with the line under

2021-09-17 14:57 UTC, tadam50 commented on single-line-diagram-core/src/main/java/com/powsybl/sld/library/Component.java
> +    public Component(@JsonProperty("") ComponentMetadata metadata) {
Do you want to keep Component class and remove ComponentMetadata class ?

2021-09-20 08:01 UTC, flo-dup commented on single-line-diagram-core/src/main/java/com/powsybl/sld/library/Component.java
> +    public Component(@JsonProperty("") ComponentMetadata metadata) {
I'd rather keep Component class and remove ComponentMetadata.

2021-09-20 08:31 UTC, flo-dup approved these changes

2021-09-20 08:54 UTC, merged