Intern cell explicit positionning
powsybl/powsybl-single-line-diagram pull request #292
Opened 2021-10-22 13:23 UTC by BenoitJeanson

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
feature

**What is the current behavior?** *(You can also link to an open issue here)*
Only ExternCells have an order.

**What is the new behavior (if this is a feature change)?**
Introduce ability to define an order, and explicit orientation to a **vertical InternCell**. 
No Extension is available in iidm to support that. See TestInternCellExplicitPosition.java

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2021-11-08 15:10 UTC, flo-dup requested changes

2021-11-08 15:10 UTC, flo-dup commented on single-line-diagram-core/src/test/java/com/powsybl/sld/raw/TestLanesWithUnileg.java
> +        toSVG(g, "testLanesWithUnileg.svg");
Either remove or add an assert to check the SVG string.

2021-11-08 15:10 UTC, flo-dup commented on single-line-diagram-core/src/main/java/com/powsybl/sld/model/AbstractBusCell.java
> +    public int getOrder() {
I'm wondering, don't you think we should also use `OptionalInt` here?

2021-11-09 15:24 UTC, flo-dup commented on single-line-diagram-core/src/main/java/com/powsybl/sld/model/Node.java
> +    public Optional<Integer> getOrder() {
Forget this if you use `null` instead of `-1`

2021-11-10 10:12 UTC, BenoitJeanson commented on single-line-diagram-core/src/main/java/com/powsybl/sld/layout/BlockPositionner.java
> +            // ArrayList<>(ss.getVerticalInternCells()));
No ;-)

2021-11-10 10:18 UTC, BenoitJeanson commented on single-line-diagram-core/src/main/java/com/powsybl/sld/layout/BlockPositionner.java
> +            ArrayList<BusCell> verticalCells = new ArrayList<>(ss.getVerticalInternCells());
done

2021-12-16 16:05 UTC, merged